# ==============================================================================
# PROJECT METADATA
# ==============================================================================

name: roadmap

description: "Flutter Developer Roadmap"

publish_to: 'none'

version: 0.0.1+1

homepage: https://roadmap.plugfox.dev

repository: https://github.com/plugfox/roadmap

issue_tracker: https://github.com/plugfox/roadmap/issues


#funding:
#  - https://www.buymeacoffee.com/
#  - https://www.patreon.com/
#  - https://boosty.to/

#topics:
#  -
#  -

#platforms:
#  web:

#screenshots:
#  - description: 'Screenshot 1'
#    path: screenshot_1.png


# ==============================================================================
# PROJECT STRUCTURE
# ==============================================================================

# https://dart.dev/tools/pub/workspaces
#workspace:
#  - packages/ui

#executables:
#  - tool/roadmap_schema.dart
#  - tool/roadmap_compile.dart
#  - tool/roadmap_fake.dart


# ==============================================================================
# DEPENDENCIES
# ==============================================================================

environment:
  sdk: '>=3.6.1 <4.0.0'

dependencies:
  # Localization
  intl: ^0.20.2

  # Annotation
  #json_annotation: ^4.9.0
  l: ^5.0.0
  meta: any

  # Utility
  #collection: any
  #async: any
  #path: any
  #convert: any
  vector_math: ^2.1.4

  # Transport and serialization
  #flat_buffers: ^23.5.26
  protobuf: ^3.1.0

  # Web
  web: ^1.1.0

dev_dependencies:
  # Roadmap generation
  yaml: ^3.1.3

  # Linting
  lints: ^5.1.1

  # Testing
  test: any

  # Code generation
  build_runner: ^2.4.13
  build_web_compilers: ^4.1.1
  #json_serializable: ^6.8.0
